# Generated by Django 4.1 on 2022-09-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculo',
            new_name='Vehiculos',
        ),
    ]
